package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/constant"
	"go/token"
	"go/types"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	packagesPath := flag.String("packages", "api/packages.txt", "file containing package import paths to snapshot")
	checkPath := flag.String("check", "", "compare generated snapshot with this file")
	flag.Parse()

	paths, err := readPackageList(*packagesPath)
	if err != nil {
		exitErr(err)
	}
	out, err := snapshot(paths)
	if err != nil {
		exitErr(err)
	}
	if *checkPath != "" {
		want, err := os.ReadFile(*checkPath)
		if err != nil {
			exitErr(err)
		}
		if !bytes.Equal(normalizeNewline(want), out) {
			exitErr(fmt.Errorf("API snapshot differs from %s; regenerate with go run ./cmd/swf-api-snapshot -packages %s > %s", *checkPath, *packagesPath, *checkPath))
		}
		return
	}
	_, _ = os.Stdout.Write(out)
}

func readPackageList(path string) ([]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out []string
	for i, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, " ") || strings.Contains(line, "\t") {
			return nil, fmt.Errorf("%s:%d: package path must not contain whitespace", path, i+1)
		}
		out = append(out, line)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no packages listed", path)
	}
	return out, nil
}

func snapshot(paths []string) ([]byte, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
	}
	pkgs, err := packages.Load(cfg, paths...)
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(pkgs) > 0 {
		return nil, fmt.Errorf("failed to load packages")
	}
	byPath := make(map[string]*packages.Package, len(pkgs))
	for _, pkg := range pkgs {
		byPath[pkg.PkgPath] = pkg
	}

	var b strings.Builder
	b.WriteString("# Code generated by go run ./cmd/swf-api-snapshot -packages api/packages.txt; DO NOT EDIT.\n")
	for _, path := range paths {
		pkg := byPath[path]
		if pkg == nil || pkg.Types == nil {
			return nil, fmt.Errorf("package %s was not loaded", path)
		}
		writePackage(&b, pkg.Types)
	}
	return []byte(b.String()), nil
}

func writePackage(b *strings.Builder, pkg *types.Package) {
	q := qualifier(pkg)
	fmt.Fprintf(b, "\npackage %s\n", pkg.Path())
	scope := pkg.Scope()
	names := scope.Names()
	sort.Strings(names)
	for _, name := range names {
		if !token.IsExported(name) {
			continue
		}
		writeObject(b, pkg, scope.Lookup(name), q)
	}
}

func writeObject(b *strings.Builder, pkg *types.Package, obj types.Object, q types.Qualifier) {
	switch obj := obj.(type) {
	case *types.Const:
		fmt.Fprintf(b, "const %s %s = %s\n", obj.Name(), types.TypeString(obj.Type(), q), constValue(obj.Val()))
	case *types.Var:
		fmt.Fprintf(b, "var %s %s\n", obj.Name(), types.TypeString(obj.Type(), q))
	case *types.Func:
		fmt.Fprintf(b, "func %s %s\n", obj.Name(), signatureString(obj.Type().(*types.Signature), q))
	case *types.TypeName:
		writeType(b, pkg, obj, q)
	}
}

func writeType(b *strings.Builder, pkg *types.Package, obj *types.TypeName, q types.Qualifier) {
	if obj.IsAlias() {
		fmt.Fprintf(b, "type %s = %s\n", obj.Name(), types.TypeString(types.Unalias(obj.Type()), q))
		return
	}
	named, _ := obj.Type().(*types.Named)
	if named == nil {
		fmt.Fprintf(b, "type %s %s\n", obj.Name(), types.TypeString(obj.Type().Underlying(), q))
		return
	}
	switch u := named.Underlying().(type) {
	case *types.Struct:
		fmt.Fprintf(b, "type %s struct\n", obj.Name())
		writeStructFields(b, u, q)
	case *types.Interface:
		fmt.Fprintf(b, "type %s interface\n", obj.Name())
		writeInterface(b, u, q)
	default:
		fmt.Fprintf(b, "type %s %s\n", obj.Name(), types.TypeString(u, q))
	}
	writeMethods(b, obj.Name(), named, q)
}

func writeStructFields(b *strings.Builder, st *types.Struct, q types.Qualifier) {
	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		if !field.Exported() {
			continue
		}
		prefix := "field"
		if field.Embedded() {
			prefix = "embedded"
		}
		tag := st.Tag(i)
		if tag != "" {
			fmt.Fprintf(b, "  %s %s %s `%s`\n", prefix, field.Name(), types.TypeString(field.Type(), q), tag)
		} else {
			fmt.Fprintf(b, "  %s %s %s\n", prefix, field.Name(), types.TypeString(field.Type(), q))
		}
	}
}

func writeInterface(b *strings.Builder, iface *types.Interface, q types.Qualifier) {
	iface = iface.Complete()
	for i := 0; i < iface.NumEmbeddeds(); i++ {
		fmt.Fprintf(b, "  embedded %s\n", types.TypeString(iface.EmbeddedType(i), q))
	}
	methods := make([]*types.Func, 0, iface.NumExplicitMethods())
	for i := 0; i < iface.NumExplicitMethods(); i++ {
		method := iface.ExplicitMethod(i)
		if method.Exported() {
			methods = append(methods, method)
		}
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name() < methods[j].Name() })
	for _, method := range methods {
		fmt.Fprintf(b, "  method %s %s\n", method.Name(), signatureString(method.Type().(*types.Signature), q))
	}
}

func writeMethods(b *strings.Builder, typeName string, named *types.Named, q types.Qualifier) {
	methods := make([]*types.Func, 0, named.NumMethods())
	for i := 0; i < named.NumMethods(); i++ {
		method := named.Method(i)
		if method.Exported() {
			methods = append(methods, method)
		}
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name() < methods[j].Name() })
	for _, method := range methods {
		fmt.Fprintf(b, "method %s.%s %s\n", typeName, method.Name(), signatureString(method.Type().(*types.Signature), q))
	}
}

func signatureString(sig *types.Signature, q types.Qualifier) string {
	return types.TypeString(sig, q)
}

func qualifier(current *types.Package) types.Qualifier {
	return func(pkg *types.Package) string {
		if pkg == nil || pkg.Path() == current.Path() {
			return ""
		}
		return pkg.Path()
	}
}

func constValue(v constant.Value) string {
	if v == nil {
		return "<nil>"
	}
	return v.ExactString()
}

func normalizeNewline(in []byte) []byte {
	return []byte(strings.ReplaceAll(string(in), "\r\n", "\n"))
}

func exitErr(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
